blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/cpsit/t3hauler/blob/master/README.md
    about: Check the documentation for usage examples and guides
  - name: Discussions
    url: https://github.com/cpsit/t3hauler/discussions
    about: Ask questions and discuss ideas with the community
